services:
  api:
    environment: 
      - PGUSER=futureproof
      - PGHOST=db
      - PGPASSWORD=librarypass
      - PGDATABASE=habit_test
      - PGPORT=5432
      - NODE_ENV=test
    depends_on:
      - db
    command: bash -c "npm install && npm test"

  db:
    expose: 
      - "5432"
    volumes:
      - "test_dbdata:/var/lib/postgresql/data"
    environment: 
      - POSTGRES_DB=habit_test
      - POSTGRES_USER=futureproof
      - POSTGRES_PASSWORD=librarypass
volumes:
  test_dbdata:
